version: '3'
services:
  app:
    image: immobylette--api-main:feat-couscous
    ports:
      - 8080:8080
      - 8081:8081
    environment:
      - SPRING_PROFILES_ACTIVE=local
      - DB_HOST=db
      - DB_NAME=immobylette
      - DB_USER=postgre
      - DB_PASSWORD=fakesecret
    links:
      - db:database
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=immobylette
      - POSTGRES_USER=postgre
      - POSTGRES_PASSWORD=fakesecret
    ports:
      - '5432:5432'
