name: CI/CD Immobylette Api Main

on:
  push:
    branches:
      - '*'
  pull_request:
    types: [opened, synchronize]

jobs:
  build:
    name: Build Snapshot and Push
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' || !(github.ref == 'refs/heads/main')

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get branch names.
        id: branch-names
        uses: tj-actions/branch-names@v8

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version-file: '.java-version'

      - name: Build with Maven
        run: mvn clean install -DskipTests

      - name: Format image name
        id: format-image-name
        run: |
          echo "Running on pr: ${{ steps.branch-names.outputs.current_branch }}"
          BRANCH_FORMATTED=$(echo "${{ steps.branch-names.outputs.current_branch }}" | sed 's/[^a-zA-Z0-9]/-/g' | tr '[:upper:]' '[:lower:]')
          echo "Branch : ${BRANCH_FORMATTED}" 
          echo "TAG_NAME=$BRANCH_FORMATTED" >> "$GITHUB_OUTPUT"



      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/setup-gcloud@v0
        with:
          export_default_credentials: true
          service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Configure Docker
        run: |
          gcloud auth configure-docker europe-west9-docker.pkg.dev

#      - name: Login to GAR
#        uses: docker/login-action@v3
#        with:
#          registry: europe-west9-docker.pkg.dev
#          username: oauth2accesstoken
#          password: ${{ steps.auth.outputs.access_token }}

      - name: Build and Push Snapshot
        env:
          TAG_NAME: ${{ steps.format-image-name.outputs.TAG_NAME }}
        run: |
          echo "Building image for branch $TAG_NAME"
          docker build -t europe-west9-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/immobylette--api-main/immobylette--api-main:TAG_NAME .
          docker push europe-west9-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/immobylette--api-main/immobylette--api-main:TAG_NAME
  

  release:
    name: Build Release and Push
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Tag and Publish Release
        run: |
          # Your commands to build and publish the release container